FROM mcr.microsoft.com/playwright:v1.62.1-noble

WORKDIR /app/frontend
COPY package.json package-lock.json ./
RUN npm ci
RUN npx playwright install chromium
COPY . .

CMD ["npx", "playwright", "test", "--config=playwright.config.ts"]
