services:
  backend:
    # Uses the latest stable release.
    # For the latest development version, replace ":latest" with ":develop".
    image: ghcr.io/codebude/librislog/librislog-api:latest
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  frontend:
    # Uses the latest stable release.
    # For the latest development version, replace ":latest" with ":develop".
    image: ghcr.io/codebude/librislog/librislog:latest
    ports:
      - "8001:80"
    depends_on:
      - backend
    restart: unless-stopped
