"""add theme and custom_theme to user_settings

Revision ID: bfe919c8b47b
Revises: b5c3d9a2e1f4
Create Date: 2026-05-22 15:22:58.100122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe919c8b47b'
down_revision: Union[str, Sequence[str], None] = 'b5c3d9a2e1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersettings', sa.Column('theme', sa.String(length=20), nullable=False, server_default='light'))
    op.add_column('usersettings', sa.Column('custom_theme', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersettings', 'custom_theme')
    op.drop_column('usersettings', 'theme')
    # ### end Alembic commands ###
